version: "3"

services:
  web:
    build:
      context: './web'
    image: te-sh/yqui-web
    volumes:
      - './web:/app'
      - '/app/node_modules'
  ws:
    build:
      context: './ws'
    image: te-sh/yqui-ws
    volumes:
      - './ws:/app'
  proxy:
    image: nginx:1.19.0-alpine
    ports:
      - '8085:8085'
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - web
      - ws
