version: "3"

services:
  web:
    build:
      context: './web'
      dockerfile: './Dockerfile.prod'
    image: te-sh/yqui-web-prod
  ws:
    build:
      context: './ws'
      dockerfile: './Dockerfile.prod'
    image: te-sh/yqui-ws-prod
    volumes:
      - './ws/log:/app/log'
    restart: on-failure
  proxy:
    image: nginx:1.19.1-alpine
    ports:
      - '8085:8085'
    volumes:
      - ./proxy/proxy.prod.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - web
      - ws
