version: '3'

services:
  web:
    build:
      context: './web'
      dockerfile: './Dockerfile.prod'
    image: tesh/yqui-web
  ws:
    build:
      context: './ws'
      dockerfile: './Dockerfile.prod'
    image: tesh/yqui-ws
    volumes:
      - './ws/log:/home/yqui/app/log'
    environment:
      - COMPOSE_PROJECT_NAME
    restart: on-failure
  proxy:
    image: nginx:1.19.6-alpine
    ports:
      - '${PORT:-8080}:8080'
    volumes:
      - './proxy/proxy.prod.conf:/etc/nginx/conf.d/proxy.conf:ro'
    depends_on:
      - web
      - ws
