version: "3"

services:
  web:
    build:
      context: './web'
    image: tesh/yqui-web-dev
    volumes:
      - './web:/home/node/app'
      - '/home/node/app/node_modules'
    stdin_open: true
  ws:
    build:
      context: './ws'
    image: tesh/yqui-ws-dev
    volumes:
      - './ws:/app'
    environment:
      - COMPOSE_PROJECT_NAME
  proxy:
    image: nginx:1.19.6-alpine
    ports:
      - ${PORT:-8080}:8080
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - web
      - ws
