version: '3'

services:
  web:
    build:
      context: './web'
    image: tesh/yqui-web-dev
    volumes:
      - './web:/home/node/app'
      - '/home/node/app/node_modules'
    stdin_open: true
  ws:
    build:
      context: './ws'
    image: tesh/yqui-ws-dev
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - './ws:/app'
  proxy:
    image: nginx:1.19.7-alpine
    ports:
      - '${PORT:-8080}:8080'
    volumes:
      - './proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro'
    depends_on:
      - web
      - ws
  test:
    build:
      context: './test'
    image: tesh/yqui-e2e-test
    volumes:
      - './test:/home/node/test'
      - '/home/node/test/node_modules'
    environment:
      - TEST_TARGET
    cap_add:
      - SYS_ADMIN
    shm_size: 1024m
    tty: true
    command: ['/bin/sh']
