#! /bin/sh

args=$(getopt -o '' -l skip-build,skip-yqui,skip-test -- "$@") || exit 1
eval "set -- $args"

while [ $# -gt 0 ]; do
    case $1 in
        --skip-build) SKIP_BUILD=1; shift ;;
        --skip-yqui) SKIP_YQUI=1; shift ;;
        --skip-test) SKIP_TEST=1; shift ;;
        --) shift; break ;;
    esac
done

if [ -z $SKIP_BUILD ]; then
    git pull
    docker-compose --file docker-compose.prod.yml build
fi

if [ -z $SKIP_YQUI ]; then
    export COMPOSE_PROJECT_NAME=yqui
    docker-compose down
    PORT=8085 docker-compose --file docker-compose.prod.yml up -d
fi

if [ -z $SKIP_TEST ]; then
    export COMPOSE_PROJECT_NAME=test
    docker-compose down
    PORT=8800 docker-compose --file docker-compose.prod.yml up -d
fi

docker system prune --volumes --force
