require:
  - rubocop-rspec

AllCops:
  Exclude:
    - spec/spec_helper.rb
  NewCops: enable
  TargetRubyVersion: 3.0

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
