FROM golang:1.14.4-alpine3.12

WORKDIR /app

ADD . ./
RUN apk add git \
 && go get gopkg.in/natefinch/lumberjack.v2 \
 && go get github.com/gorilla/websocket \
 && go build

ENV YQUI_ENV prod

CMD ["./app"]
