FROM node:14.15.4-alpine3.12 AS builder

WORKDIR /app

ADD . ./
RUN yarn install \
 && yarn build

FROM nginx:1.19.6-alpine

RUN apk update \
 && apk upgrade \
 && rm -rf /var/cache/apk/*

COPY --from=builder /app/build /app/build
